version: "3.9"
services:
  astrobot:
    build: .
    container_name: astrobot
    environment:
      TELEGRAM_TOKEN: "8336037368:AAEmGFL5AQhi3CLKMZ9VeEIqMTjbs08RUiU"
      ASTRO_DB: /data/astro_users.sqlite3
      ASTRO_TZ: "America/Detroit"
      ASTRO_TAD_PATH: "usa/detroit"
      ASTRO_DAILY_HOUR: "17"
      ASTRO_DAILY_MIN: "0"
      ASTRO_USE_GEMINI: "1"   # default LLM on; /mode lets each user override
      GEMINI_API_KEY: "AIzaSyDhNwRvdTK5w2HTb8IoYsW45SUj26ojUnQ"      # optional but recommended when ASTRO_USE_GEMINI=1
      GEMINI_MODEL: "models/gemini-2.0-flash-001"
      SERPAPI_API_KEY: "2c220fed774894b0110a2260851cfbb24434f3d45bb4a52f0a48e8766683779f"       # optional for web search in LLM mode
      USE_LLM: "false"   # set to "true" to default to LLM mode for new users
      IPGEOLOCATION_API_KEY: "" # optional for moonrise/set
      ASTRO_LLM_FETCH_PAGES: "0"
    volumes:
      - astrobot_data:/data
    restart: unless-stopped
volumes:
  astrobot_data: